[tasks.default]
dependencies = ["test"]

[tasks.test]
command = "trunk"
args = ["serve", "--open"]

[tasks.clean]
command = "trunk"
args = ["clean"]

[tasks.build]
command = "trunk"
args = ["build", "--release"]
dependencies = ["clean"]

[tasks.deploy]
command = "neocities"
args = ["push", "--prune", "dist/"]
dependencies = ["build"]
